apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: message-mirror
  namespace: message-mirror
  labels:
    app: message-mirror
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: message-mirror
