apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: message-mirror
  namespace: message-mirror
  labels:
    app: message-mirror
    release: prometheus
spec:
  selector:
    matchLabels:
      app: message-mirror
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
