//go:build integration
// +build integration

package core

import (
	"context"
	"fmt"
	"testing"
	"time"

	"github.com/IBM/sarama"
	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/wait"
)

// TestIntegration_KafkaMessageFlow 测试Kafka完整消息流
func TestIntegration_KafkaMessageFlow(t *testing.T) {
	if testing.Short() {
		t.Skip("跳过集成测试")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()

	// 启动Zookeeper
	zkReq := testcontainers.ContainerRequest{



















































































































































































































}	t.Logf("RabbitMQ Management地址: localhost:%s", mgmtPort.Port())	t.Logf("RabbitMQ AMQP地址: localhost:%s", amqpPort.Port())	}		t.Fatalf("获取Management端口失败: %v", err)	if err != nil {	mgmtPort, err := container.MappedPort(ctx, "15672")	// 获取Management端口	}		t.Fatalf("获取AMQP端口失败: %v", err)	if err != nil {	amqpPort, err := container.MappedPort(ctx, "5672")	// 获取AMQP端口	defer container.Terminate(ctx)	}		return		t.Logf("启动RabbitMQ容器失败（可能缺少Docker）: %v", err)	if err != nil {	})		Started:          true,		ContainerRequest: req,	container, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{	}		WaitingFor: wait.ForLog("Server startup complete"),		},			"RABBITMQ_DEFAULT_PASS":     "guest",			"RABBITMQ_DEFAULT_USER":     "guest",		Env: map[string]string{		ExposedPorts: []string{"5672/tcp", "15672/tcp"},		Image:        "rabbitmq:3.12-management",	req := testcontainers.ContainerRequest{	// RabbitMQ容器请求	defer cancel()	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)	}		t.Skip("跳过集成测试")	if testing.Short() {func TestIntegration_RabbitMQContainer(t *testing.T) {// TestIntegration_RabbitMQContainer 测试RabbitMQ容器启动（为future集成做准备）}	}		t.Log("MirrorMaker初始化成功")		}			t.Error("Worker数量应该是2")		if mm.config.Mirror.WorkerCount != 2 {		// 如果成功创建，验证基本属性	if mm != nil {	}		return		t.Logf("初始化MirrorMaker（预期失败，Kafka未运行）: %v", err)	if err != nil {	mm, err := NewMirrorMaker(config)	// 尝试初始化MirrorMaker（会因为无法连接到Kafka而失败，但这是正常的）	}		},			Enabled: false,		Dedup: DedupConfig{		},			Enabled: true,		Retry: RetryConfig{		},			Enabled: false,		Server: ServerConfig{		},			AsyncBufferSize: 100,			MaxArchiveFiles: 3,			RotateInterval:  24 * time.Hour,			StatsInterval:   10 * time.Second,			FilePath:        "/tmp/test.log",		Log: LogConfig{		},			WorkerCount: 2,		Mirror: MirrorConfig{		},			Topic:   "target-topic",			Brokers: []string{"localhost:19092"},		Target: TargetConfig{		},			},				"group_id": "test-group",				"topic":   "test-topic",				"brokers": []interface{}{"localhost:19092"}, // 使用未使用的端口避免真实连接			Config: map[string]interface{}{			Type: "kafka",		Source: SourceConfig{	config := &Config{	}		t.Skip("跳过集成测试")	if testing.Short() {func TestIntegration_MirrorMakerInitialization(t *testing.T) {// TestIntegration_MirrorMakerInitialization 测试MirrorMaker初始化}	}		t.Logf("配置验证：%v", err)	if err := validateConfig(config); err != nil {	// 这个验证应该通过（即使Kafka没有运行）	}		},			WorkerCount: 4,		Mirror: MirrorConfig{		},			Topic:   "target-topic",			Brokers: []string{"localhost:9092"},		Target: TargetConfig{		},			},				"group_id": "test-group",				"topic":   "test-topic",				"brokers": []interface{}{"localhost:9092"},			Config: map[string]interface{}{			Type: "kafka",		Source: SourceConfig{	config := &Config{	// 测试基本配置验证	}		t.Skip("跳过集成测试")	if testing.Short() {func TestIntegration_ConfigValidation(t *testing.T) {// TestIntegration_ConfigValidation 测试配置在容器环境中的验证}	}		t.Log("消息发送超时（正常情况）")	case <-time.After(5 * time.Second):		t.Log("消息已发送")	case producer.Input() <- testMsg:	select {	}		Value: sarama.StringEncoder("test-value"),		Key:   sarama.StringEncoder("test-key"),		Topic: "test-topic",	testMsg := &sarama.ProducerMessage{	// 发送测试消息	defer producer.Close()	}		return		t.Logf("创建生产者失败（正常情况，Kafka容器可能还未完全就绪）: %v", err)	if err != nil {	producer, err := sarama.NewAsyncProducer([]string{kafkaAddr}, config)	config.Producer.RequiredAcks = sarama.WaitForAll	config.Version = sarama.V2_8_0_0	config := sarama.NewConfig()	// 创建生产者	time.Sleep(2 * time.Second)	// 等待Kafka完全启动	t.Logf("Kafka地址: %s", kafkaAddr)	kafkaAddr := fmt.Sprintf("localhost:%s", port.Port())	}		t.Fatalf("获取端口失败: %v", err)	if err != nil {	port, err := kafkaContainer.MappedPort(ctx, "9092")	// 获取Kafka端口	defer kafkaContainer.Terminate(ctx)	}		t.Fatalf("启动Kafka失败: %v", err)	if err != nil {	})		Started:          true,		ContainerRequest: kafkaReq,	kafkaContainer, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{	}		WaitingFor: wait.ForLog("started"),		},			"KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR": "1",			"KAFKA_INTER_BROKER_LISTENER_NAME":     "PLAINTEXT",			"KAFKA_LISTENER_SECURITY_PROTOCOL_MAP": "PLAINTEXT:PLAINTEXT",			"KAFKA_ADVERTISED_LISTENERS":           "PLAINTEXT://localhost:9092",			"KAFKA_ZOOKEEPER_CONNECT":              "host.docker.internal:2181",			"KAFKA_BROKER_ID":                      "1",		Env: map[string]string{		ExposedPorts: []string{"9092/tcp"},		Image:        "confluentinc/cp-kafka:7.5.0",	kafkaReq := testcontainers.ContainerRequest{	// 启动Kafka	defer zkContainer.Terminate(ctx)	}		t.Fatalf("启动Zookeeper失败: %v", err)	if err != nil {	})		Started:          true,		ContainerRequest: zkReq,	zkContainer, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{	}		WaitingFor: wait.ForLog("binding to port"),		},			"ZOOKEEPER_CLIENT_PORT": "2181",		Env: map[string]string{		Image: "confluentinc/cp-zookeeper:7.5.0",